// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StoreType int32

const (
	StoreType_BTreeDisk     StoreType = 0
	StoreType_BPlusTreeDisk StoreType = 1
)

var StoreType_name = map[int32]string{
	0: "BTreeDisk",
	1: "BPlusTreeDisk",
}

var StoreType_value = map[string]int32{
	"BTreeDisk":     0,
	"BPlusTreeDisk": 1,
}

func (x StoreType) String() string {
	return proto.EnumName(StoreType_name, int32(x))
}

func (StoreType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12a4512b96b720f2, []int{0}
}

type Status struct {
	//code = 1 means success
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a4512b96b720f2, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type MessageResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a4512b96b720f2, []int{1}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ConnectionRequest struct {
	Type                 StoreType `protobuf:"varint,1,opt,name=type,proto3,enum=service.StoreType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConnectionRequest) Reset()         { *m = ConnectionRequest{} }
func (m *ConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionRequest) ProtoMessage()    {}
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a4512b96b720f2, []int{2}
}

func (m *ConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionRequest.Unmarshal(m, b)
}
func (m *ConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionRequest.Marshal(b, m, deterministic)
}
func (m *ConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionRequest.Merge(m, src)
}
func (m *ConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectionRequest.Size(m)
}
func (m *ConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionRequest proto.InternalMessageInfo

func (m *ConnectionRequest) GetType() StoreType {
	if m != nil {
		return m.Type
	}
	return StoreType_BTreeDisk
}

type CloseConnectionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseConnectionRequest) Reset()         { *m = CloseConnectionRequest{} }
func (m *CloseConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*CloseConnectionRequest) ProtoMessage()    {}
func (*CloseConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a4512b96b720f2, []int{3}
}

func (m *CloseConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseConnectionRequest.Unmarshal(m, b)
}
func (m *CloseConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseConnectionRequest.Marshal(b, m, deterministic)
}
func (m *CloseConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseConnectionRequest.Merge(m, src)
}
func (m *CloseConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_CloseConnectionRequest.Size(m)
}
func (m *CloseConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseConnectionRequest proto.InternalMessageInfo

type GetKVRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKVRequest) Reset()         { *m = GetKVRequest{} }
func (m *GetKVRequest) String() string { return proto.CompactTextString(m) }
func (*GetKVRequest) ProtoMessage()    {}
func (*GetKVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a4512b96b720f2, []int{4}
}

func (m *GetKVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKVRequest.Unmarshal(m, b)
}
func (m *GetKVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKVRequest.Marshal(b, m, deterministic)
}
func (m *GetKVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKVRequest.Merge(m, src)
}
func (m *GetKVRequest) XXX_Size() int {
	return xxx_messageInfo_GetKVRequest.Size(m)
}
func (m *GetKVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetKVRequest proto.InternalMessageInfo

func (m *GetKVRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetKVResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKVResponse) Reset()         { *m = GetKVResponse{} }
func (m *GetKVResponse) String() string { return proto.CompactTextString(m) }
func (*GetKVResponse) ProtoMessage()    {}
func (*GetKVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a4512b96b720f2, []int{5}
}

func (m *GetKVResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKVResponse.Unmarshal(m, b)
}
func (m *GetKVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKVResponse.Marshal(b, m, deterministic)
}
func (m *GetKVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKVResponse.Merge(m, src)
}
func (m *GetKVResponse) XXX_Size() int {
	return xxx_messageInfo_GetKVResponse.Size(m)
}
func (m *GetKVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetKVResponse proto.InternalMessageInfo

func (m *GetKVResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetKVResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SetKVRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetKVRequest) Reset()         { *m = SetKVRequest{} }
func (m *SetKVRequest) String() string { return proto.CompactTextString(m) }
func (*SetKVRequest) ProtoMessage()    {}
func (*SetKVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a4512b96b720f2, []int{6}
}

func (m *SetKVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetKVRequest.Unmarshal(m, b)
}
func (m *SetKVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetKVRequest.Marshal(b, m, deterministic)
}
func (m *SetKVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetKVRequest.Merge(m, src)
}
func (m *SetKVRequest) XXX_Size() int {
	return xxx_messageInfo_SetKVRequest.Size(m)
}
func (m *SetKVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetKVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetKVRequest proto.InternalMessageInfo

func (m *SetKVRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetKVRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RemoveKVRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveKVRequest) Reset()         { *m = RemoveKVRequest{} }
func (m *RemoveKVRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveKVRequest) ProtoMessage()    {}
func (*RemoveKVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a4512b96b720f2, []int{7}
}

func (m *RemoveKVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveKVRequest.Unmarshal(m, b)
}
func (m *RemoveKVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveKVRequest.Marshal(b, m, deterministic)
}
func (m *RemoveKVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveKVRequest.Merge(m, src)
}
func (m *RemoveKVRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveKVRequest.Size(m)
}
func (m *RemoveKVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveKVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveKVRequest proto.InternalMessageInfo

func (m *RemoveKVRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RemoveKVResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Check                bool     `protobuf:"varint,2,opt,name=check,proto3" json:"check,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveKVResponse) Reset()         { *m = RemoveKVResponse{} }
func (m *RemoveKVResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveKVResponse) ProtoMessage()    {}
func (*RemoveKVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a4512b96b720f2, []int{8}
}

func (m *RemoveKVResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveKVResponse.Unmarshal(m, b)
}
func (m *RemoveKVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveKVResponse.Marshal(b, m, deterministic)
}
func (m *RemoveKVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveKVResponse.Merge(m, src)
}
func (m *RemoveKVResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveKVResponse.Size(m)
}
func (m *RemoveKVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveKVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveKVResponse proto.InternalMessageInfo

func (m *RemoveKVResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RemoveKVResponse) GetCheck() bool {
	if m != nil {
		return m.Check
	}
	return false
}

type ExistKVRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistKVRequest) Reset()         { *m = ExistKVRequest{} }
func (m *ExistKVRequest) String() string { return proto.CompactTextString(m) }
func (*ExistKVRequest) ProtoMessage()    {}
func (*ExistKVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a4512b96b720f2, []int{9}
}

func (m *ExistKVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistKVRequest.Unmarshal(m, b)
}
func (m *ExistKVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistKVRequest.Marshal(b, m, deterministic)
}
func (m *ExistKVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistKVRequest.Merge(m, src)
}
func (m *ExistKVRequest) XXX_Size() int {
	return xxx_messageInfo_ExistKVRequest.Size(m)
}
func (m *ExistKVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistKVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExistKVRequest proto.InternalMessageInfo

func (m *ExistKVRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ExistKVResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Check                bool     `protobuf:"varint,2,opt,name=check,proto3" json:"check,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistKVResponse) Reset()         { *m = ExistKVResponse{} }
func (m *ExistKVResponse) String() string { return proto.CompactTextString(m) }
func (*ExistKVResponse) ProtoMessage()    {}
func (*ExistKVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a4512b96b720f2, []int{10}
}

func (m *ExistKVResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistKVResponse.Unmarshal(m, b)
}
func (m *ExistKVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistKVResponse.Marshal(b, m, deterministic)
}
func (m *ExistKVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistKVResponse.Merge(m, src)
}
func (m *ExistKVResponse) XXX_Size() int {
	return xxx_messageInfo_ExistKVResponse.Size(m)
}
func (m *ExistKVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistKVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExistKVResponse proto.InternalMessageInfo

func (m *ExistKVResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ExistKVResponse) GetCheck() bool {
	if m != nil {
		return m.Check
	}
	return false
}

func init() {
	proto.RegisterEnum("service.StoreType", StoreType_name, StoreType_value)
	proto.RegisterType((*Status)(nil), "service.Status")
	proto.RegisterType((*MessageResponse)(nil), "service.MessageResponse")
	proto.RegisterType((*ConnectionRequest)(nil), "service.ConnectionRequest")
	proto.RegisterType((*CloseConnectionRequest)(nil), "service.CloseConnectionRequest")
	proto.RegisterType((*GetKVRequest)(nil), "service.GetKVRequest")
	proto.RegisterType((*GetKVResponse)(nil), "service.GetKVResponse")
	proto.RegisterType((*SetKVRequest)(nil), "service.SetKVRequest")
	proto.RegisterType((*RemoveKVRequest)(nil), "service.RemoveKVRequest")
	proto.RegisterType((*RemoveKVResponse)(nil), "service.RemoveKVResponse")
	proto.RegisterType((*ExistKVRequest)(nil), "service.ExistKVRequest")
	proto.RegisterType((*ExistKVResponse)(nil), "service.ExistKVResponse")
}

func init() { proto.RegisterFile("api/proto/service.proto", fileDescriptor_12a4512b96b720f2) }

var fileDescriptor_12a4512b96b720f2 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5f, 0x8b, 0xd3, 0x40,
	0x10, 0x6f, 0xbc, 0x4b, 0xef, 0x32, 0x77, 0xbd, 0xf4, 0xd6, 0xf3, 0x1a, 0xf3, 0x62, 0x59, 0x41,
	0x8b, 0x60, 0x0b, 0x11, 0x44, 0x2a, 0x08, 0xb6, 0x16, 0x1f, 0x8a, 0x52, 0x37, 0xa5, 0x0f, 0xbe,
	0xc5, 0x38, 0x68, 0x68, 0xcd, 0xc6, 0x6c, 0x52, 0xcc, 0x57, 0xf2, 0x53, 0x4a, 0x37, 0xc9, 0x36,
	0xa6, 0x35, 0xa0, 0xf8, 0x96, 0xd9, 0xf9, 0xfd, 0x19, 0x66, 0x7e, 0x04, 0x7a, 0x5e, 0x14, 0x8c,
	0xa2, 0x98, 0x27, 0x7c, 0x24, 0x30, 0xde, 0x06, 0x3e, 0x0e, 0x65, 0x45, 0xce, 0x8a, 0x92, 0x3a,
	0xd0, 0x76, 0x13, 0x2f, 0x49, 0x05, 0x21, 0x70, 0xea, 0xf3, 0xcf, 0x68, 0x69, 0x7d, 0x6d, 0xa0,
	0x33, 0xf9, 0x4d, 0x6e, 0x40, 0xc7, 0x38, 0xe6, 0xb1, 0x75, 0xa7, 0xaf, 0x0d, 0x0c, 0x96, 0x17,
	0x74, 0x0c, 0xe6, 0x3b, 0x14, 0xc2, 0xfb, 0x82, 0x0c, 0x45, 0xc4, 0x43, 0x81, 0xe4, 0x31, 0xb4,
	0x85, 0x94, 0x91, 0xf4, 0x0b, 0xc7, 0x1c, 0x96, 0x7e, 0xb9, 0x3a, 0x2b, 0xda, 0xf4, 0x25, 0x5c,
	0x4f, 0x79, 0x18, 0xa2, 0x9f, 0x04, 0x3c, 0x64, 0xf8, 0x3d, 0x45, 0x91, 0x90, 0x47, 0x70, 0x9a,
	0x64, 0x51, 0x6e, 0x7d, 0xe5, 0x90, 0x0a, 0x97, 0xc7, 0xb8, 0xcc, 0x22, 0x64, 0xb2, 0x4f, 0x2d,
	0xb8, 0x9d, 0x6e, 0xb8, 0xc0, 0x03, 0x05, 0xda, 0x87, 0xcb, 0xb7, 0x98, 0xcc, 0x57, 0xa5, 0x62,
	0x17, 0x4e, 0xd6, 0x98, 0x49, 0x41, 0x83, 0xed, 0x3e, 0xe9, 0x7b, 0xe8, 0x14, 0x88, 0xbf, 0x1c,
	0x79, 0xb7, 0x84, 0xad, 0xb7, 0x49, 0xb1, 0x5c, 0x82, 0x2c, 0xe8, 0x73, 0xb8, 0x74, 0x1b, 0x1d,
	0xff, 0xc0, 0x7b, 0x08, 0x26, 0xc3, 0x6f, 0x7c, 0x8b, 0x4d, 0xc3, 0x7e, 0x80, 0xee, 0x1e, 0xf4,
	0x0f, 0xf3, 0xfa, 0x5f, 0xd1, 0x5f, 0x4b, 0xdf, 0x73, 0x96, 0x17, 0x94, 0xc2, 0xd5, 0xec, 0x47,
	0x20, 0x1a, 0x77, 0xb4, 0x00, 0x53, 0x61, 0xfe, 0x8b, 0xeb, 0x93, 0xa7, 0x60, 0xa8, 0x23, 0x92,
	0x0e, 0x18, 0x93, 0x65, 0x8c, 0xf8, 0x26, 0x10, 0xeb, 0x6e, 0x8b, 0x5c, 0x43, 0x67, 0xb2, 0xd8,
	0xa4, 0x42, 0x3d, 0x69, 0xce, 0xcf, 0x13, 0xb8, 0x99, 0x63, 0xb6, 0xda, 0x6d, 0x4a, 0xf2, 0xdc,
	0xdc, 0x8c, 0xcc, 0xe0, 0xa2, 0x38, 0xfa, 0xc7, 0xc5, 0x7c, 0x45, 0x6c, 0x35, 0xc5, 0x41, 0x14,
	0x6c, 0x4b, 0xf5, 0x6a, 0x21, 0xa5, 0x2d, 0xc2, 0xe0, 0x6e, 0x2d, 0x40, 0x52, 0xee, 0xc1, 0x5e,
	0xee, 0x68, 0xbc, 0x1a, 0x35, 0x5f, 0x80, 0x2e, 0x83, 0x45, 0xee, 0x29, 0x50, 0x35, 0x8a, 0xf6,
	0x6d, 0xfd, 0x59, 0x31, 0xc7, 0xa0, 0xbb, 0x35, 0x66, 0x35, 0x52, 0x8d, 0xae, 0xaf, 0xe1, 0xbc,
	0x4c, 0x08, 0xd9, 0xe3, 0x6a, 0xc9, 0xb2, 0xef, 0x1f, 0xe9, 0x28, 0x89, 0x57, 0x70, 0x56, 0x5c,
	0x9b, 0xf4, 0x14, 0xee, 0xf7, 0x8c, 0x54, 0x46, 0xa8, 0x05, 0x83, 0xb6, 0x3e, 0xb5, 0xe5, 0xaf,
	0xe4, 0xd9, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10, 0xbb, 0xdb, 0xf6, 0x65, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KeyValueStoreServiceClient is the client API for KeyValueStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeyValueStoreServiceClient interface {
	// connect ZP_KV service
	ConnectZPKV(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	// close connection ZP_KV serivce
	CloseConnectionZPKV(ctx context.Context, in *CloseConnectionRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	// get key-value connection db
	GetKV(ctx context.Context, in *GetKVRequest, opts ...grpc.CallOption) (*GetKVResponse, error)
	// set key-value connection db
	SetKV(ctx context.Context, in *SetKVRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	// remove key-value connection db
	RemoveKV(ctx context.Context, in *RemoveKVRequest, opts ...grpc.CallOption) (*RemoveKVResponse, error)
	// check key-value exists connection db
	ExistKV(ctx context.Context, in *ExistKVRequest, opts ...grpc.CallOption) (*ExistKVResponse, error)
}

type keyValueStoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewKeyValueStoreServiceClient(cc *grpc.ClientConn) KeyValueStoreServiceClient {
	return &keyValueStoreServiceClient{cc}
}

func (c *keyValueStoreServiceClient) ConnectZPKV(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/service.KeyValueStoreService/ConnectZPKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreServiceClient) CloseConnectionZPKV(ctx context.Context, in *CloseConnectionRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/service.KeyValueStoreService/CloseConnectionZPKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreServiceClient) GetKV(ctx context.Context, in *GetKVRequest, opts ...grpc.CallOption) (*GetKVResponse, error) {
	out := new(GetKVResponse)
	err := c.cc.Invoke(ctx, "/service.KeyValueStoreService/GetKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreServiceClient) SetKV(ctx context.Context, in *SetKVRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/service.KeyValueStoreService/SetKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreServiceClient) RemoveKV(ctx context.Context, in *RemoveKVRequest, opts ...grpc.CallOption) (*RemoveKVResponse, error) {
	out := new(RemoveKVResponse)
	err := c.cc.Invoke(ctx, "/service.KeyValueStoreService/RemoveKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreServiceClient) ExistKV(ctx context.Context, in *ExistKVRequest, opts ...grpc.CallOption) (*ExistKVResponse, error) {
	out := new(ExistKVResponse)
	err := c.cc.Invoke(ctx, "/service.KeyValueStoreService/ExistKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyValueStoreServiceServer is the server API for KeyValueStoreService service.
type KeyValueStoreServiceServer interface {
	// connect ZP_KV service
	ConnectZPKV(context.Context, *ConnectionRequest) (*MessageResponse, error)
	// close connection ZP_KV serivce
	CloseConnectionZPKV(context.Context, *CloseConnectionRequest) (*MessageResponse, error)
	// get key-value connection db
	GetKV(context.Context, *GetKVRequest) (*GetKVResponse, error)
	// set key-value connection db
	SetKV(context.Context, *SetKVRequest) (*MessageResponse, error)
	// remove key-value connection db
	RemoveKV(context.Context, *RemoveKVRequest) (*RemoveKVResponse, error)
	// check key-value exists connection db
	ExistKV(context.Context, *ExistKVRequest) (*ExistKVResponse, error)
}

// UnimplementedKeyValueStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKeyValueStoreServiceServer struct {
}

func (*UnimplementedKeyValueStoreServiceServer) ConnectZPKV(ctx context.Context, req *ConnectionRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectZPKV not implemented")
}
func (*UnimplementedKeyValueStoreServiceServer) CloseConnectionZPKV(ctx context.Context, req *CloseConnectionRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseConnectionZPKV not implemented")
}
func (*UnimplementedKeyValueStoreServiceServer) GetKV(ctx context.Context, req *GetKVRequest) (*GetKVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKV not implemented")
}
func (*UnimplementedKeyValueStoreServiceServer) SetKV(ctx context.Context, req *SetKVRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetKV not implemented")
}
func (*UnimplementedKeyValueStoreServiceServer) RemoveKV(ctx context.Context, req *RemoveKVRequest) (*RemoveKVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveKV not implemented")
}
func (*UnimplementedKeyValueStoreServiceServer) ExistKV(ctx context.Context, req *ExistKVRequest) (*ExistKVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExistKV not implemented")
}

func RegisterKeyValueStoreServiceServer(s *grpc.Server, srv KeyValueStoreServiceServer) {
	s.RegisterService(&_KeyValueStoreService_serviceDesc, srv)
}

func _KeyValueStoreService_ConnectZPKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServiceServer).ConnectZPKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.KeyValueStoreService/ConnectZPKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServiceServer).ConnectZPKV(ctx, req.(*ConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStoreService_CloseConnectionZPKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServiceServer).CloseConnectionZPKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.KeyValueStoreService/CloseConnectionZPKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServiceServer).CloseConnectionZPKV(ctx, req.(*CloseConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStoreService_GetKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServiceServer).GetKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.KeyValueStoreService/GetKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServiceServer).GetKV(ctx, req.(*GetKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStoreService_SetKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServiceServer).SetKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.KeyValueStoreService/SetKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServiceServer).SetKV(ctx, req.(*SetKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStoreService_RemoveKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServiceServer).RemoveKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.KeyValueStoreService/RemoveKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServiceServer).RemoveKV(ctx, req.(*RemoveKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStoreService_ExistKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServiceServer).ExistKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.KeyValueStoreService/ExistKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServiceServer).ExistKV(ctx, req.(*ExistKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeyValueStoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.KeyValueStoreService",
	HandlerType: (*KeyValueStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectZPKV",
			Handler:    _KeyValueStoreService_ConnectZPKV_Handler,
		},
		{
			MethodName: "CloseConnectionZPKV",
			Handler:    _KeyValueStoreService_CloseConnectionZPKV_Handler,
		},
		{
			MethodName: "GetKV",
			Handler:    _KeyValueStoreService_GetKV_Handler,
		},
		{
			MethodName: "SetKV",
			Handler:    _KeyValueStoreService_SetKV_Handler,
		},
		{
			MethodName: "RemoveKV",
			Handler:    _KeyValueStoreService_RemoveKV_Handler,
		},
		{
			MethodName: "ExistKV",
			Handler:    _KeyValueStoreService_ExistKV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/service.proto",
}
